### ISSUE TITLE
include apertium-news-scraper

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-tools#2]
currently just called scraper, I think

**Comment by jonorthwash** [comment]
Sorry, not yet imported to github:
http://svn.code.sf.net/p/apertium/svn/trunk/apertium-tools/scraper/

**Comment by jonorthwash** [comment]
also the WikiExtractor

**Comment by jonorthwash** [comment]
WikiExtractor seems to be included: https://github.com/apertium/WikiExtractor

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-news-scrapers
